import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          
      <div className="flex justify-between p-3 "  >
          <div className="">
          <LeftSidebar/>
          </div>
          <div className="">
          {children}

          </div>
          <div className="bg-[#ABDBE3] w-[24rem] p-4">
          <RightSidebar />
          </div>

        </div>        
      </body>
    </html>
  </ClerkProvider>
  );
}